### ISSUE TITLE
Building parts of Spack environments on different nodes: option 2 (no environment chaining)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-ARC/hpc-spack#56]
Right now, when creating an environment in our site with spacksites, it does this:

```
# create our site, check out spack in it
spacksites/spacksites create hk-initial-stack

# create an environment in our site from a yaml file and install it
spacksites/spacksites install-env hk-initial-stack compiler first_compiler.yaml

# what that runs:

# SPACKSITES: Have set spacks's external compiler and python dependencies - now calling spack env create compiler /lustre/scratch/ccspapp/spack/0.21/hpc-spack/spacksites/spack-env-templates/dev1/first_compiler.yaml
==> Created environment 'compiler' in /lustre/shared/ucl/apps/spack/0.21/hk-initial-stack/spack/var/spack/environments/compiler
==> You can activate this environment with:
==>   spack env activate compiler
# SPACKSITES: Now calling:  /lustre/scratch/ccspapp/spack/0.21/hpc-spack/spacksites/process-env-scripts/spack-deps-spack-env-run.sh /shared/ucl/apps/spack/0.21/hk-initial-stack/spack/share/spack/setup-env.sh spack -e compiler install
# SPACKSITES: have set SPACK_DISABLE_LOCAL_CONFIG=1
# SPACKSITES: have set HPC_SPACK_ROOT=/lustre/scratch/ccspapp/spack/0.21/hpc-spack
# SPACKSITES: Have set spacks's external compiler and python dependencies - now calling spack -e compiler install
==> Concretized autoconf@2.69
 -   k2zx6ae  autoconf@2.69%gcc@11.2.1 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rhel7-cascadelake
...
# concretisation continues
 ```

To be able to install parts of the concretised environment using different nodes (eg GPU nodes when needed) we need to create the environment, concretise it, then specify to only install some chunks of it at a time. 

Option 2 here assumes that we will have one main yaml file per cluster (that can include others), specify the whole environment in those, then do some parsing of what we've concretized to specify what we are installing right now. 

```
spack env create myriad-opt2 /home/ccspapp/Scratch/spack/0.21/hpc-spack/spacksites/spack-env-templates/dev1/build/myriad.yaml
spack -e myriad-opt2 concretize -f

# create a makefile from our concretized environment
spack -e myriad-opt2 env depfile > /shared/ucl/apps/spack/0.21/hk-initial-stack/provenance/Makefile
```

Now we can install specific bits of the environment like this, but want to be able to check the yaml files we pass in to grab a list of certain packages instead of doing this by hand.
```
make -j ${NUMBER_OF_PARALLEL_BUILDS} install/dbcsr-2.6.0-ru5b6hayhmebidxtnloji4jxucq2raow
```

We can make our initial .yaml file have includes - was thinking `myriad.yaml`, `base.yaml`, `gpu.yaml`, `gpu-on-gpu.yaml` for right now. On Myriad, we would use the `myriad.yaml` which would only have myriad-only packages in that file, and include `base` for packages that we intend to install everywhere, `gpu` for gpu packages, and `gpu-on-gpu` packages for packages that must be installed on a GPU node. 

Then we want to be able to install `base` and `myriad` packages on CPU, `gpu-on-gpu` on GPU, followed by `gpu` back on CPU, to make sure any GPU dependencies that needed to be done on GPU are already done.

**Comment by heatherkellyucl** [comment]
My `myriad.yaml` only looks like this right now, as we have bcftools, samtools etc installed everywhere so they are in base.

```
spack:
  specs:
  - matrix:
    - - 'vcftools@0.1.16'
    - - '%gcc@12.3.0'
  concretizer:
    unify: when_possible
  view: false
  include:
  - base.yaml
  - gpu.yaml
  - gpu-on-gpu.yaml
  modules:
    default:
      tcl:
        projections:
          all:  '{name}/{version}/{compiler.name}-{compiler.version}'
          ^mpi: '{name}/{version}-{^mpi.name}/{compiler.name}-{compiler.version}'
          ^cuda: '{name}/{version}-cuda/{compiler.name}-{compiler.version}'
          ^cuda+mpi: '{name}/{version}-{^mpi.name}-cuda/{compiler.name}-{compiler.version}'
    prefix_inspections:
      lib: ["LD_LIBRARY_PATH", "LIBRARY_PATH"]
      lib64: ["LD_LIBRARY_PATH", "LIBRARY_PATH"]
```

(I also tried extending the module projections for cuda and cuda+mpi, this isn't tested yet so no idea if that works).
