### ISSUE TITLE
Deployment module layout

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-ARC/hpc-spack#65]
Right now we have module directories of 
`core, applications, libraries, compilers, development, bundles`
and `beta, dept, workarounds` which are only used when other modules are loaded.

There are two ways of doing a similar layout in Spack:

1) using modulesets

2) entirely using projections

I think that modulesets is going to be less complicated to maintain because projections apply rules in order and that becomes harder to think about when you have different prefixes but then want rules like adding "cuda" and "mpi" to names within those.

**Comment by heatherkellyucl** [comment]
In both of those cases you do need to specify the packages that the moduleset includes (or excludes) and what the projections apply to. 

As long as modules are not the ones with prefixes like `compilers` or `mpi` then moving them between always-visible modulesets should not break anything in user jobs because they retain the same module name, so we can add modulesets over time if we wish and if they seem necessary - right now the applications and libraries sections are enormous.

We also need an atomic module refresh operation like we do at present for when we regenerate any of the moduletree. 

Modulesets look like this:

```
  modules:
    # using modulesets to get flat categories
    compilers:
      roots:
        tcl: /shared/ucl/apps/spack/0.23/deploy/2025-02/modules/compilers

      tcl:
        hide_implicits: true
        all:
          autoload: direct
          # conflict with all other compilers in this section
          conflict:
            - 'compilers'
        include: ['gcc', 'intel-one-api', 'intel']

        projections:
          all:  'compilers/{name}/{version}/{compiler.name}-{compiler.version}'

    mpi:
      roots:
        tcl: /shared/ucl/apps/spack/0.23/deploy/2025-02/modules/mpi

      tcl:
        hide_implicits: true
        all:
          autoload: direct
          # conflict with all other mpis in this section
          conflict:
            - 'mpi'
        include: ['openmpi', 'intel-mpi', 'intel-oneapi-mpi']

        projections:
          all:  'mpi/{name}/{version}/{compiler.name}-{compiler.version}'

    libraries:
      roots:
        tcl: /shared/ucl/apps/spack/0.23/deploy/2025-02/modules/libraries

      tcl:
        hide_implicits: true
        all:
          autoload: direct
          # conflict with everything of same name
          conflict:
            - '{name}'
        include: ['boost', 'cgal', 'eigen', 'fftw', 'gsl', 'gulp', 'hdf5', 'htslib', 'libxc', 'mesa', 'metis', 'mumps',
                  'netcdf-c', 'netcdf-fortran', 'numactl', 'openblas', 'parmetis', 'quip', 'scalapack', 'suitesparse,
                  'udunits', 'vtk']
        projections:
          # Named packages where we have more than one installed so need different module names.
          # First match is picked, so more specific need to be at top. 'all' can be anywhere.
          # Add omp for openmp variants.
          fftw +openmp ^mpi: '{name}/{version}-{^mpi.name}-omp/{compiler.name}-{compiler.version}'
          openblas threads=openmp: '{name}/{version}-omp/{compiler.name}-{compiler.version}'

          ^cuda ^mpi: '{name}/{version}-{^mpi.name}-cuda/{compiler.name}-{compiler.version}'
          ^mpi: '{name}/{version}-{^mpi.name}/{compiler.name}-{compiler.version}'
          ^cuda: '{name}/{version}-cuda/{compiler.name}-{compiler.version}'
          all:  '{name}/{version}/{compiler.name}-{compiler.version}'

    default:
      roots:
        tcl: /shared/ucl/apps/spack/0.23/deploy/2025-02/modules/applications

      tcl:
        hide_implicits: true
        all:
          autoload: direct
          # conflict with everything of same name
          conflict:
            - '{name}'

        projections:
          # Named packages where we have more than one installed so need different module names.
          # First match is picked, so more specific need to be at top. 'all' can be anywhere.
          # Add omp for openmp variants.

          ^cuda ^mpi: '{name}/{version}-{^mpi.name}-cuda/{compiler.name}-{compiler.version}'
          ^mpi: '{name}/{version}-{^mpi.name}/{compiler.name}-{compiler.version}'
          ^cuda: '{name}/{version}-cuda/{compiler.name}-{compiler.version}'
          all:  '{name}/{version}/{compiler.name}-{compiler.version}'

```

There is some repetition in `projections` here. 

The default everything-else set is currently being put under `applications` - do we want that?

Should `cuda` or `gpu` be its own moduleset? Possible issue when the cuda-enabled version of an application is also the non-cuda version.

`r` and `python` could potentially be modulesets in terms of numbers of likely modules, although we're meant to be updating and removing versions to refresh the stack approx 6-monthly so there might not be so many to need it. (Especially with the view for python bundle packages). Implicit python dependencies of specific packages are currently hidden.

I think everything like nvhpc can go into the `compilers` section and conflict with the rest, since there's the `gcc-runtime` which is like our `gcc-libs`.

Need to check on `nag` when we add that since we have that as a compiler but also in the libraries section - see if it has a nag-runtime equivalent or if that isn't needed.

**Comment by heatherkellyucl** [comment]
Doing it all with projections would look something like this (but I think that conflict line wouldn't work?), but anything you wanted to call out as cuda and/or mpi for libraries would need to be in the rule for that package name, not a general case:

```
    default:
      roots:
        tcl: /shared/ucl/apps/spack/0.23/deploy/2025-02/modules

      tcl:
        hide_implicits: true
        all:
          autoload: direct
          conflict:
            - 'compilers'
            - 'mpi'
            - 'libraries/{name}'
            - 'applications/{name}'

        projections:
          # alternative to modulesets - sections need an initial dir
          # all the mpi
          openmpi: 'mpi/{name}/{version}/{compiler.name}-{compiler.version}'
          intel-mpi: 'mpi/{name}/{version}/{compiler.name}-{compiler.version}'
          intel-oneapi-mpi: 'mpi/{name}/{version}/{compiler.name}-{compiler.version}'

          # all the compilers
          gcc: 'compilers/{name}/{version}'
          intel-one-api: 'compilers/{name}/{version}'
          intel: 'compilers/{name}/{version}'
          # nvhpc: 

          # the libraries 
          fftw +openmp ^mpi: 'libraries/{name}/{version}-{^mpi.name}-omp/{compiler.name}-{compiler.version}'
          fftw: 'libraries/{name}/{version}'/{compiler.name}-{compiler.version}'
          hdf5:' libraries/{name}/{version}'/{compiler.name}-{compiler.version}'
          openblas threads=openmp: 'libraries/{name}/{version}-omp/{compiler.name}-{compiler.version}'
          openblas: 'libraries/{name}/{version}'/{compiler.name}-{compiler.version}'
          plumed: 'libraries/{name}/{version}'/{compiler.name}-{compiler.version}'

          # everything else as applications
          ^cuda ^mpi: 'applications/{name}/{version}-{^mpi.name}-cuda/{compiler.name}-{compiler.version}'
          ^mpi: 'applications/{name}/{version}-{^mpi.name}/{compiler.name}-{compiler.version}'
          ^cuda: 'applications/{name}/{version}-cuda/{compiler.name}-{compiler.version}'
          all:  'applications/{name}/{version}/{compiler.name}-{compiler.version}'
          
```
